acme_store:
    resource: "@AcmeStoreBundle/Controller/"
    type: annotation
    prefix: /store

acme_hello:
    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
    prefix: /say

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type: annotation
    prefix: /admin