acme_hello_homepage:
    path:     /homepage/
    defaults: { _controller: AcmeHelloBundle:Default:index }
    
acme_hello:
    path: /hello/{name}
    defaults: { _controller: AcmeHelloBundle:Hello:index }
